config/routes.rb
CloudTranslation::Application.routes.draw do

  devise_for :clients do
    match '/client' => "works#index", :as => :client_root

  end
  resources :works

  match 'tasks/:id/change_status/:status' => 'tasks#change_status', :as => "task_status"

  devise_for :workers do
    match '/worker' => "tasks#index", :as => :worker_root
  end
  resources :tasks
  root :to => "home#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
has_many :works
mount_uploader :document, DocumentUploader
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :work
  belongs_to :worker

def self.search(search)
  if search
    where(:status =>"Untranslated" )
  else
   scoped
  end
end

end

app/models/work.rb
class Work < ActiveRecord::Base
  require "tactful_tokenizer"
  belongs_to :client
  has_many :tasks
  after_create :create_tasks
  validates :content, :presence =>true
  validates :to, :presence =>true
  validates :from, :presence =>true

  private
      def create_tasks
           @tactful_tokenizer ||= TactfulTokenizer::Model.new
            result =  @tactful_tokenizer.tokenize_text(self.content)
            task_reward = (self.reward / result.length)
            0.upto(result.length - 1) do |i|
              task1  = self.tasks.build(:content => result[i], :reward => task_reward)
              task1.save
            end
       end

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     if client_signed_in?
      redirect_to works_path
    elsif worker_signed_in?
      redirect_to tasks_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
helper_method :sort_column , :sort_direction

  def index
 #  @tasks                     = Task.where(:status =>"Untranslated" ).paginate(:page => params[:page], :per_page => 10)
    @tasks                     = Task.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasks                     = Task.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tasks }
    end
  end
  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task                      = Task.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end
  # GET /tasks/1/edit
  def edit
    @task                      = Task.find(params[:id])
  end
  # POST /tasks
  # POST /tasks.json
  def create
    @task                      = Task.new(params[:task])
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Translation was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task                      = Task.find(params[:id])
    respond_to do |format|
      @task.worker_id          = current_worker.id
      @task.status             = "Pending"
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Your Translation has been submitted' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task                      = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
  def change_status
    @task                      = Task.find(params[:id])
     if params[:status] == "Approved"
      @task.Approved           = true
      @task.status             = "Translated"
      @task.save
      @workers                 = Worker.find(@task.worker_id)
      @workers.credit          = @workers.credit  + @task.reward
      @workers.works_completed = @workers.works_completed + 1
      @workers.save
       end
      redirect_to work_path(@task.work_id)
       if params[:status] == "Rejected"
        @task.Approved         = false
        @task.status           = "Untranslated"
        @task.save
        redirect_to work_path(@task.work_id)
    end
  end
private
  def sort_column
   Task.column_names.include?(params[:sort]) ? params[:sort] : "content"
  end
  def sort_direction
   %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.json
  def index
    @works                               = Work.where(:client_id => current_client.id).paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work                                = current_client.works.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work                                = current_client.works.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @work }
    end
  end
  # GET /works/1/edit
  def edit
    @work                                = Work.find(params[:id])
  end
  # POST /works
  # POST /works.json
  def create
    @work                                = current_client.works.new(params[:work])
    respond_to do |format|
      if (current_client.budget >= @work.reward)
        if @work.save
          current_client.budget          = current_client.budget - @work.reward
          current_client.works_submitted = current_client.works_submitted + 1
          current_client.save
          format.html { redirect_to @work, notice: 'Work was successfully created.' }
          format.json { render json: @work, status: :created, location: @work }
        else
          format.html { render action: "new" }
          format.json { render json: @work.errors, status: :unprocessable_entity }
        end
      else
        # flash[:notice]                 = "You do not have enough budget"
        format.html { redirect_to @work, notice: 'You do not have enough budget  .' }
      end
   end
end
  # PUT /works/1
  # PUT /works/1.json
  def update
    @work                                = Works.find(params[:id])
    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work                                = Work.find(params[:id])
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_header.html.erb
<header>
  <hgroup>
    <a href="#" title="Cloud Translation"><img src="../images/logo.png" alt="Cloud Translation" /></a>
    <h1>Cloud Translation</h1>
    <h2>Most Reliable translation</h2>
  </hgroup>
  <div id ="top_bar">

  <% if client_signed_in?%>
    <%= link_to "Home", root_path %>
    <span id = "welcome_message">Client: <%=current_client.email%> </span>
    <span >Budget: <%=current_client.budget%></span> &nbsp;
    <%= link_to "Sign Out", destroy_client_session_path, method: :delete %>
    <% end %>

    <% if worker_signed_in?%>
      <%= link_to "Home", root_path %>
      <span id = "welcome_message">Worker: <%=current_worker.email%> </span>
      <span >Credit : <%=current_worker.credit%> </span>  &nbsp;
      <%= link_to "Sign Out", destroy_worker_session_path, method: :delete %>
      <% end %>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloud Translation</title>
  <%= stylesheet_link_tag    "application" ,"style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if not (client_signed_in? || worker_signed_in?) %>
       <%= link_to 'Login as Client', client_session_path %> <br/>
       <%= link_to 'Login as Worker', worker_session_path %>
    <% end %>
  <%= yield %>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
<% if @task.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

  <ul>
    <% @task.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="translation area">
  <div class = "translation_box">
    <%= f.label "Text to be Translated" %><br />
    <%= @task.work.from     %><br />
    <%= f.text_area :content ,:disabled=>true%>
  </div>
  <div class = "translation_box">
    <%= f.label :translated_text %><br />
    <%= @task.work.to     %><br />
    <%= f.text_area :translated_text %>
  </div>
</div>
  <div class="actions">
    <%= f.submit :value => "Submit"%>
  </div>
  <% end %>

app/views/tasks/_tasks.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

app/views/tasks/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @task %> |
<%= link_to 'Back to List', tasks_path %>

app/views/tasks/index.html.erb
<h1>Available Translation Tasks</h1>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= form_tag tasks_path, :method => 'get', :id =>"tasks_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="tasks"><%= render 'tasks' %></div>
<% end %>
<table class="tasklist" width = "100%">
  <tr>
    <th width=450 px><%= sortable "content","Original" %></th>
    <th><%= sortable "from" ,"From"  %></th>
    <th><%= sortable "to" ,"To"%></th>
    <th><%= sortable "reward" ,"Reward" %></th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
    <td  style = "text-align: justify" ><%= task.content.truncate(200) %></td>
    <td><%= task.work.from %></td>
    <td><%= task.work.to %></td>
    <td><%= task.reward.round(2) %></td>
    <td><%= link_to 'Translate', edit_task_path(task) %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @tasks %>
<br />

app/views/tasks/index.js.erb
$("#tasks").html("<%= escape_javascript(render("tasks")) %>");

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Original Text:</b>
  <%= @tasks.content %>
</p>
<p>
  <b>Your Translation:</b>
  <%= @tasks.translated_text %>
</p>
<p>
  <b>Reward:</b>
  <%= @tasks.reward.round(2) %>
</p>
<%= link_to 'Back', tasks_path %>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
<% if @work.errors.any? %>
<div id        = "error_explanation">
  <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>
  <ul>
    <% @work.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
 <div id        = "form">
  <% languages = ["English", "Newari" , "Nepali", "French","Japanese","Chinese","Hindi"]  %>


  <div class   = "field" style="float:left">
    <%= f.label :from %><br />
    <%= select( "work", "from", languages, {:prompt => true}) %>
  </div>
  <div class   = "field" style="float:right">
    <%= f.label :to %><br />
    <%= select( "work", "to", languages, {:prompt => true}) %>
  </div>
  <div class   = "field" style = "clear:both">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class   = "field">
    <%= f.label :reward %><br />
    <%= f.text_field :reward %>
  </div>
  <div class   = "field">
    <%= f.label :additional_info %><br />
    <%= f.text_area :additional_info, :id => "additional_info" %>
  </div>
  <div class   = "actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<%= link_to 'Submit New ', new_work_path %>
<h1>Submitted works</h1>
<table id ="Worklist" >
  <tr>
    <th>Content</th>
    <th>From</th>
    <th>To</th>
    <th>Reward</th>
    <th>Additional info</th>
    <th></th>
    <th></th>
  </tr>
<% @works.each do |work| %>
  <tr>
    <td width =380px class="justify"><%= work.content.truncate(200) %></td>
    <td><%= work.from %></td>
    <td><%= work.to %></td>
    <td><%= work.reward %></td>
    <td width =180px class="justify"><%= work.additional_info %></td>
    <td><%= link_to 'Details', work %></td>
    <td><%= link_to 'Delete', work, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @works %>
<br />

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p>
  <b>Content:</b>
  <%= @work.content %>
</p>

<p>
  <b>From:</b>
  <%= @work.from %>
</p>

<p>
  <b>To:</b>
  <%= @work.to %>
</p>

<p>
  <b>Reward:</b>
  <%= @work.reward %>
</p>

<p>
  <b>Additional info:</b>
  <%= @work.additional_info %>
</p>

<p>
  <b>Translated text:</b>
  <%= @work.translated_text %>
</p>

<table id="translation_client_view">
  <tr>
    <th width= 350px>Original</th>
    <th width= 350px>Translation</th>
    <th width= 350px>Action</th>
  </tr>

  <% @work.tasks.each do |task| %>
  <!-- <%# if (task.Approved != true && !task.translated_text.nil?)%>    -->
  <tr>
    <td><%= task.content %></td>
    <td><%= task.translated_text %></td>
    <% if task.translated_text != nil %>
     <% if task.status == "Translated" &&  %>
        <td>Approved</td>
     <% else %>
        <td><%= link_to 'Approve',   task_status_path(task,"Approved") %>  ||
        <%= link_to 'Reject',   task_status_path(task,"Rejected") %></td>
     <% end%>
      <% else %>
      <td>Not Translated</td>
  <% end%>
  </tr>
  <% #end %>
  <% end %>

</table>

<%= link_to 'Back', works_path %>